[package]
name = "pipemind_rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "pipemind_rust"
path = "src/lib.rs"

[[bin]]
name = "pipemind_rust"
path = "src/main.rs"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.29.0"